<?php

/**
 * BaseStoryRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $story_id
 * @property integer $1_votes
 * @property integer $2_votes
 * @property integer $3_votes
 * @property integer $4_votes
 * @property integer $5_votes
 * @property float $average_vote
 * @property Story $Story
 * 
 * @method integer     getStoryId()      Returns the current record's "story_id" value
 * @method integer     get1Votes()       Returns the current record's "1_votes" value
 * @method integer     get2Votes()       Returns the current record's "2_votes" value
 * @method integer     get3Votes()       Returns the current record's "3_votes" value
 * @method integer     get4Votes()       Returns the current record's "4_votes" value
 * @method integer     get5Votes()       Returns the current record's "5_votes" value
 * @method float       getAverageVote()  Returns the current record's "average_vote" value
 * @method Story       getStory()        Returns the current record's "Story" value
 * @method StoryRating setStoryId()      Sets the current record's "story_id" value
 * @method StoryRating set1Votes()       Sets the current record's "1_votes" value
 * @method StoryRating set2Votes()       Sets the current record's "2_votes" value
 * @method StoryRating set3Votes()       Sets the current record's "3_votes" value
 * @method StoryRating set4Votes()       Sets the current record's "4_votes" value
 * @method StoryRating set5Votes()       Sets the current record's "5_votes" value
 * @method StoryRating setAverageVote()  Sets the current record's "average_vote" value
 * @method StoryRating setStory()        Sets the current record's "Story" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseStoryRating extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_rating');
        $this->hasColumn('story_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('1_votes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('2_votes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('3_votes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('4_votes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('5_votes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('average_vote', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}