<?php

/**
 * BaseHome
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $is_active
 * @property string $feature_html
 * @property string $feature_copy_intro
 * @property string $feature_copy_extended
 * @property string $callout_html
 * @property integer $story1_id
 * @property string $story1_image_url
 * @property integer $story2_id
 * @property string $story2_image_url
 * @property integer $story3_id
 * @property string $story3_image_url
 * @property integer $story4_id
 * @property string $story4_image_url
 * @property Story $Story1
 * @property Story $Story2
 * @property Story $Story3
 * @property Story $Story4
 * 
 * @method integer getId()                    Returns the current record's "id" value
 * @method boolean getIsActive()              Returns the current record's "is_active" value
 * @method string  getFeatureHtml()           Returns the current record's "feature_html" value
 * @method string  getFeatureCopyIntro()      Returns the current record's "feature_copy_intro" value
 * @method string  getFeatureCopyExtended()   Returns the current record's "feature_copy_extended" value
 * @method string  getCalloutHtml()           Returns the current record's "callout_html" value
 * @method integer getStory1Id()              Returns the current record's "story1_id" value
 * @method string  getStory1ImageUrl()        Returns the current record's "story1_image_url" value
 * @method integer getStory2Id()              Returns the current record's "story2_id" value
 * @method string  getStory2ImageUrl()        Returns the current record's "story2_image_url" value
 * @method integer getStory3Id()              Returns the current record's "story3_id" value
 * @method string  getStory3ImageUrl()        Returns the current record's "story3_image_url" value
 * @method integer getStory4Id()              Returns the current record's "story4_id" value
 * @method string  getStory4ImageUrl()        Returns the current record's "story4_image_url" value
 * @method Story   getStory1()                Returns the current record's "Story1" value
 * @method Story   getStory2()                Returns the current record's "Story2" value
 * @method Story   getStory3()                Returns the current record's "Story3" value
 * @method Story   getStory4()                Returns the current record's "Story4" value
 * @method Home    setId()                    Sets the current record's "id" value
 * @method Home    setIsActive()              Sets the current record's "is_active" value
 * @method Home    setFeatureHtml()           Sets the current record's "feature_html" value
 * @method Home    setFeatureCopyIntro()      Sets the current record's "feature_copy_intro" value
 * @method Home    setFeatureCopyExtended()   Sets the current record's "feature_copy_extended" value
 * @method Home    setCalloutHtml()           Sets the current record's "callout_html" value
 * @method Home    setStory1Id()              Sets the current record's "story1_id" value
 * @method Home    setStory1ImageUrl()        Sets the current record's "story1_image_url" value
 * @method Home    setStory2Id()              Sets the current record's "story2_id" value
 * @method Home    setStory2ImageUrl()        Sets the current record's "story2_image_url" value
 * @method Home    setStory3Id()              Sets the current record's "story3_id" value
 * @method Home    setStory3ImageUrl()        Sets the current record's "story3_image_url" value
 * @method Home    setStory4Id()              Sets the current record's "story4_id" value
 * @method Home    setStory4ImageUrl()        Sets the current record's "story4_image_url" value
 * @method Home    setStory1()                Sets the current record's "Story1" value
 * @method Home    setStory2()                Sets the current record's "Story2" value
 * @method Home    setStory3()                Sets the current record's "Story3" value
 * @method Home    setStory4()                Sets the current record's "Story4" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseHome extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('home');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('feature_html', 'string', 10240, array(
             'type' => 'string',
             'length' => '10240',
             ));
        $this->hasColumn('feature_copy_intro', 'string', 10240, array(
             'type' => 'string',
             'length' => '10240',
             ));
        $this->hasColumn('feature_copy_extended', 'string', 10240, array(
             'type' => 'string',
             'length' => '10240',
             ));
        $this->hasColumn('callout_html', 'string', 10240, array(
             'type' => 'string',
             'length' => '10240',
             ));
        $this->hasColumn('story1_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('story1_image_url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('story2_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('story2_image_url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('story3_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('story3_image_url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('story4_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('story4_image_url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Story as Story1', array(
             'local' => 'story1_id',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasOne('Story as Story2', array(
             'local' => 'story2_id',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasOne('Story as Story3', array(
             'local' => 'story3_id',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasOne('Story as Story4', array(
             'local' => 'story4_id',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}