<?php

/**
 * BaseFact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_id
 * @property string $title
 * @property string $description
 * @property integer $related_entity_id
 * @property date $start
 * @property date $end
 * @property integer $created_by
 * @property integer $fact_type_id
 * @property sfGuardUser $Creator
 * @property Entity $Entity
 * @property Entity $RelatedEntity
 * @property Doctrine_Collection $Comments
 * @property Doctrine_Collection $Sources
 * @property Doctrine_Collection $Stories
 * @property FactType $FactType
 * @property FactActionRequired $ActionRequired
 * @property Doctrine_Collection $StoryFact
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getEntityId()          Returns the current record's "entity_id" value
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method integer             getRelatedEntityId()   Returns the current record's "related_entity_id" value
 * @method date                getStart()             Returns the current record's "start" value
 * @method date                getEnd()               Returns the current record's "end" value
 * @method integer             getCreatedBy()         Returns the current record's "created_by" value
 * @method integer             getFactTypeId()        Returns the current record's "fact_type_id" value
 * @method sfGuardUser         getCreator()           Returns the current record's "Creator" value
 * @method Entity              getEntity()            Returns the current record's "Entity" value
 * @method Entity              getRelatedEntity()     Returns the current record's "RelatedEntity" value
 * @method Doctrine_Collection getComments()          Returns the current record's "Comments" collection
 * @method Doctrine_Collection getSources()           Returns the current record's "Sources" collection
 * @method Doctrine_Collection getStories()           Returns the current record's "Stories" collection
 * @method FactType            getFactType()          Returns the current record's "FactType" value
 * @method FactActionRequired  getActionRequired()    Returns the current record's "ActionRequired" value
 * @method Doctrine_Collection getStoryFact()         Returns the current record's "StoryFact" collection
 * @method Fact                setId()                Sets the current record's "id" value
 * @method Fact                setEntityId()          Sets the current record's "entity_id" value
 * @method Fact                setTitle()             Sets the current record's "title" value
 * @method Fact                setDescription()       Sets the current record's "description" value
 * @method Fact                setRelatedEntityId()   Sets the current record's "related_entity_id" value
 * @method Fact                setStart()             Sets the current record's "start" value
 * @method Fact                setEnd()               Sets the current record's "end" value
 * @method Fact                setCreatedBy()         Sets the current record's "created_by" value
 * @method Fact                setFactTypeId()        Sets the current record's "fact_type_id" value
 * @method Fact                setCreator()           Sets the current record's "Creator" value
 * @method Fact                setEntity()            Sets the current record's "Entity" value
 * @method Fact                setRelatedEntity()     Sets the current record's "RelatedEntity" value
 * @method Fact                setComments()          Sets the current record's "Comments" collection
 * @method Fact                setSources()           Sets the current record's "Sources" collection
 * @method Fact                setStories()           Sets the current record's "Stories" collection
 * @method Fact                setFactType()          Sets the current record's "FactType" value
 * @method Fact                setActionRequired()    Sets the current record's "ActionRequired" value
 * @method Fact                setStoryFact()         Sets the current record's "StoryFact" collection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseFact extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fact');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('entity_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 2147483647, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '2147483647',
             ));
        $this->hasColumn('related_entity_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('start', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('end', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('fact_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasOne('Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Entity as RelatedEntity', array(
             'local' => 'related_entity_id',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasMany('FactComment as Comments', array(
             'local' => 'id',
             'foreign' => 'fact_id'));

        $this->hasMany('FactSource as Sources', array(
             'local' => 'id',
             'foreign' => 'fact_id'));

        $this->hasMany('Story as Stories', array(
             'refClass' => 'StoryFact',
             'local' => 'fact_id',
             'foreign' => 'story_id'));

        $this->hasOne('FactType', array(
             'local' => 'fact_type_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('FactActionRequired as ActionRequired', array(
             'local' => 'id',
             'foreign' => 'fact_id'));

        $this->hasMany('StoryFact', array(
             'local' => 'id',
             'foreign' => 'fact_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}