<?php

/**
 * BaseFactSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $fact_id
 * @property string $url
 * @property integer $source_type_id
 * @property integer $is_supporting
 * @property string $title
 * @property integer $created_by
 * @property SourceType $SourceType
 * @property Fact $Fact
 * @property sfGuardUser $Creator
 * @property Doctrine_Collection $Verifications
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getFactId()         Returns the current record's "fact_id" value
 * @method string              getUrl()            Returns the current record's "url" value
 * @method integer             getSourceTypeId()   Returns the current record's "source_type_id" value
 * @method integer             getIsSupporting()   Returns the current record's "is_supporting" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method integer             getCreatedBy()      Returns the current record's "created_by" value
 * @method SourceType          getSourceType()     Returns the current record's "SourceType" value
 * @method Fact                getFact()           Returns the current record's "Fact" value
 * @method sfGuardUser         getCreator()        Returns the current record's "Creator" value
 * @method Doctrine_Collection getVerifications()  Returns the current record's "Verifications" collection
 * @method FactSource          setId()             Sets the current record's "id" value
 * @method FactSource          setFactId()         Sets the current record's "fact_id" value
 * @method FactSource          setUrl()            Sets the current record's "url" value
 * @method FactSource          setSourceTypeId()   Sets the current record's "source_type_id" value
 * @method FactSource          setIsSupporting()   Sets the current record's "is_supporting" value
 * @method FactSource          setTitle()          Sets the current record's "title" value
 * @method FactSource          setCreatedBy()      Sets the current record's "created_by" value
 * @method FactSource          setSourceType()     Sets the current record's "SourceType" value
 * @method FactSource          setFact()           Sets the current record's "Fact" value
 * @method FactSource          setCreator()        Sets the current record's "Creator" value
 * @method FactSource          setVerifications()  Sets the current record's "Verifications" collection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseFactSource extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fact_source');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('fact_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('url', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1024',
             ));
        $this->hasColumn('source_type_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('is_supporting', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SourceType', array(
             'local' => 'source_type_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Fact', array(
             'local' => 'fact_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasMany('FactSourceVerified as Verifications', array(
             'local' => 'id',
             'foreign' => 'fact_source_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}