<?php

/**
 * BaseStoryRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $story_id
 * @property integer $related_story_id
 * @property Story $Story
 * @property Story $RelatedStory
 * 
 * @method integer       getStoryId()          Returns the current record's "story_id" value
 * @method integer       getRelatedStoryId()   Returns the current record's "related_story_id" value
 * @method Story         getStory()            Returns the current record's "Story" value
 * @method Story         getRelatedStory()     Returns the current record's "RelatedStory" value
 * @method StoryRelation setStoryId()          Sets the current record's "story_id" value
 * @method StoryRelation setRelatedStoryId()   Sets the current record's "related_story_id" value
 * @method StoryRelation setStory()            Sets the current record's "Story" value
 * @method StoryRelation setRelatedStory()     Sets the current record's "RelatedStory" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseStoryRelation extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_relation');
        $this->hasColumn('story_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('related_story_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Story as RelatedStory', array(
             'local' => 'related_story_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}