<?php

/**
 * BaseFactComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $fact_id
 * @property integer $fact_score
 * @property integer $comment_score
 * @property integer $created_by
 * @property string $comment
 * @property sfGuardUser $Creator
 * @property Fact $Fact
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method integer     getFactId()        Returns the current record's "fact_id" value
 * @method integer     getFactScore()     Returns the current record's "fact_score" value
 * @method integer     getCommentScore()  Returns the current record's "comment_score" value
 * @method integer     getCreatedBy()     Returns the current record's "created_by" value
 * @method string      getComment()       Returns the current record's "comment" value
 * @method sfGuardUser getCreator()       Returns the current record's "Creator" value
 * @method Fact        getFact()          Returns the current record's "Fact" value
 * @method FactComment setId()            Sets the current record's "id" value
 * @method FactComment setFactId()        Sets the current record's "fact_id" value
 * @method FactComment setFactScore()     Sets the current record's "fact_score" value
 * @method FactComment setCommentScore()  Sets the current record's "comment_score" value
 * @method FactComment setCreatedBy()     Sets the current record's "created_by" value
 * @method FactComment setComment()       Sets the current record's "comment" value
 * @method FactComment setCreator()       Sets the current record's "Creator" value
 * @method FactComment setFact()          Sets the current record's "Fact" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseFactComment extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fact_comment');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('fact_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('fact_score', 'integer', 2, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => '2',
             ));
        $this->hasColumn('comment_score', 'integer', 2, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => '2',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('comment', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Fact', array(
             'local' => 'fact_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}