<?php

/**
 * BaseContactMessages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $message
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method string          getMessageType()  Returns the current record's "message_type" value
 * @method string          getName()         Returns the current record's "name" value
 * @method string          getEmail()        Returns the current record's "email" value
 * @method string          getMessage()      Returns the current record's "message" value
 * @method ContactMessages setId()           Sets the current record's "id" value
 * @method ContactMessages setMessageType()  Sets the current record's "message_type" value
 * @method ContactMessages setName()         Sets the current record's "name" value
 * @method ContactMessages setEmail()        Sets the current record's "email" value
 * @method ContactMessages setMessage()      Sets the current record's "message" value_type
 * @property string $name
 * @property string $email
 * @property string $message
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method string          getMessageType()  Returns the current record's "message_type" value
 * @method string          getName()         Returns the current record's "name" value
 * @method string          getEmail()        Returns the current record's "email" value
 * @method string          getMessage()      Returns the current record's "message" value
 * @method ContactMessages setId()           Sets the current record's "id" value
 * @method ContactMessages setMessageType()  Sets the current record's "message_type" value
 * @method ContactMessages setName()         Sets the current record's "name" value
 * @method ContactMessages setEmail()        Sets the current record's "email" value
 * @method ContactMessages setMessage()      Sets the current record's "message" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseContactMessages extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact_messages');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('message_type', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '32',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('message', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1000',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}