<?php

/**
 * BaseEntityUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_id
 * @property string $url
 * @property string $title
 * @property string $urltype
 * @property integer $created_by
 * @property string $foreign_id
 * @property sfGuardUser $Creator
 * @property Entity $Entity
 * @property Doctrine_Collection $Verifications
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getEntityId()      Returns the current record's "entity_id" value
 * @method string              getUrl()           Returns the current record's "url" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getUrltype()       Returns the current record's "urltype" value
 * @method integer             getCreatedBy()     Returns the current record's "created_by" value
 * @method string              getForeignId()     Returns the current record's "foreign_id" value
 * @method sfGuardUser         getCreator()       Returns the current record's "Creator" value
 * @method Entity              getEntity()        Returns the current record's "Entity" value
 * @method Doctrine_Collection getVerifications() Returns the current record's "Verifications" collection
 * @method EntityUrl           setId()            Sets the current record's "id" value
 * @method EntityUrl           setEntityId()      Sets the current record's "entity_id" value
 * @method EntityUrl           setUrl()           Sets the current record's "url" value
 * @method EntityUrl           setTitle()         Sets the current record's "title" value
 * @method EntityUrl           setUrltype()       Sets the current record's "urltype" value
 * @method EntityUrl           setCreatedBy()     Sets the current record's "created_by" value
 * @method EntityUrl           setForeignId()     Sets the current record's "foreign_id" value
 * @method EntityUrl           setCreator()       Sets the current record's "Creator" value
 * @method EntityUrl           setEntity()        Sets the current record's "Entity" value
 * @method EntityUrl           setVerifications() Sets the current record's "Verifications" collection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseEntityUrl extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_url');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('entity_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('url', 'string', 2147483647, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '2147483647',
             ));
        $this->hasColumn('title', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));
        $this->hasColumn('urltype', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('foreign_id', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('equiv', array(
             'fields' => 
             array(
              0 => 'urltype',
              1 => 'foreign_id',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasOne('Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('EntityUrlVerified as Verifications', array(
             'local' => 'id',
             'foreign' => 'entity_url_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}