<?php

/**
 * BaseDisambiguationEntity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $disambiguation_id
 * @property integer $entity_id
 * @property Disambiguation $Disambiguation
 * @property Entity $Entity
 * 
 * @method integer              getDisambiguationId()  Returns the current record's "disambiguation_id" value
 * @method integer              getEntityId()          Returns the current record's "entity_id" value
 * @method Disambiguation       getDisambiguation()    Returns the current record's "Disambiguation" value
 * @method Entity               getEntity()            Returns the current record's "Entity" value
 * @method DisambiguationEntity setDisambiguationId()  Sets the current record's "disambiguation_id" value
 * @method DisambiguationEntity setEntityId()          Sets the current record's "entity_id" value
 * @method DisambiguationEntity setDisambiguation()    Sets the current record's "Disambiguation" value
 * @method DisambiguationEntity setEntity()            Sets the current record's "Entity" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseDisambiguationEntity extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('disambiguation_entity');
        $this->hasColumn('disambiguation_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('entity_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Disambiguation', array(
             'local' => 'disambiguation_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}