<?php

/**
 * BaseEntityAlias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_id
 * @property string $name
 * @property integer $created_by
 * @property sfGuardUser $Creator
 * @property Entity $Entity
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getEntityId()   Returns the current record's "entity_id" value
 * @method string      getName()       Returns the current record's "name" value
 * @method integer     getCreatedBy()  Returns the current record's "created_by" value
 * @method sfGuardUser getCreator()    Returns the current record's "Creator" value
 * @method Entity      getEntity()     Returns the current record's "Entity" value
 * @method EntityAlias setId()         Sets the current record's "id" value
 * @method EntityAlias setEntityId()   Sets the current record's "entity_id" value
 * @method EntityAlias setName()       Sets the current record's "name" value
 * @method EntityAlias setCreatedBy()  Sets the current record's "created_by" value
 * @method EntityAlias setCreator()    Sets the current record's "Creator" value
 * @method EntityAlias setEntity()     Sets the current record's "Entity" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseEntityAlias extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_alias');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('entity_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasOne('Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'batchUpdates' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($searchable0);
        $this->actAs($timestampable0);
    }
}