<?php

/**
 * BaseEntityUrlVerified
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_url_id
 * @property integer $score
 * @property integer $created_by
 * @property string $comment
 * @property sfGuardUser $Creator
 * @property EntityUrl $EntityUrl
 * 
 * @method integer           getId()            Returns the current record's "id" value
 * @method integer           getEntityUrlId()   Returns the current record's "entity_url_id" value
 * @method integer           getScore()         Returns the current record's "score" value
 * @method integer           getCreatedBy()     Returns the current record's "created_by" value
 * @method string            getComment()       Returns the current record's "comment" value
 * @method sfGuardUser       getCreator()       Returns the current record's "Creator" value
 * @method EntityUrl         getEntityUrl()     Returns the current record's "EntityUrl" value
 * @method EntityUrlVerified setId()            Sets the current record's "id" value
 * @method EntityUrlVerified setEntityUrlId()   Sets the current record's "entity_url_id" value
 * @method EntityUrlVerified setScore()         Sets the current record's "score" value
 * @method EntityUrlVerified setCreatedBy()     Sets the current record's "created_by" value
 * @method EntityUrlVerified setComment()       Sets the current record's "comment" value
 * @method EntityUrlVerified setCreator()       Sets the current record's "Creator" value
 * @method EntityUrlVerified setEntityUrl()     Sets the current record's "EntityUrl" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseEntityUrlVerified extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_url_verified');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('entity_url_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('score', 'integer', 2, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => '2',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('EntityUrl', array(
             'local' => 'entity_url_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}