<?php

/**
 * BaseDisambiguation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $created_by
 * @property Doctrine_Collection $Entities
 * @property Doctrine_Collection $DisambiguationEntity
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getTitle()                Returns the current record's "title" value
 * @method integer             getCreatedBy()            Returns the current record's "created_by" value
 * @method Doctrine_Collection getEntities()             Returns the current record's "Entities" collection
 * @method Doctrine_Collection getDisambiguationEntity() Returns the current record's "DisambiguationEntity" collection
 * @method Disambiguation      setId()                   Sets the current record's "id" value
 * @method Disambiguation      setTitle()                Sets the current record's "title" value
 * @method Disambiguation      setCreatedBy()            Sets the current record's "created_by" value
 * @method Disambiguation      setEntities()             Sets the current record's "Entities" collection
 * @method Disambiguation      setDisambiguationEntity() Sets the current record's "DisambiguationEntity" collection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseDisambiguation extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('disambiguation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Entity as Entities', array(
             'refClass' => 'DisambiguationEntity',
             'local' => 'disambiguation_id',
             'foreign' => 'entity_id'));

        $this->hasMany('DisambiguationEntity', array(
             'local' => 'id',
             'foreign' => 'disambiguation_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}