<?php

/**
 * BaseEntityActionRequired
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $entity_id
 * @property integer $needs_external_links
 * @property integer $needs_wiki_page
 * @property integer $needs_description
 * @property integer $needs_facts
 * @property integer $needs_subtitle
 * @property Entity $Entity
 * 
 * @method integer              getEntityId()             Returns the current record's "entity_id" value
 * @method integer              getNeedsExternalLinks()   Returns the current record's "needs_external_links" value
 * @method integer              getNeedsWikiPage()        Returns the current record's "needs_wiki_page" value
 * @method integer              getNeedsDescription()     Returns the current record's "needs_description" value
 * @method integer              getNeedsFacts()           Returns the current record's "needs_facts" value
 * @method integer              getNeedsSubtitle()        Returns the current record's "needs_subtitle" value
 * @method Entity               getEntity()               Returns the current record's "Entity" value
 * @method EntityActionRequired setEntityId()             Sets the current record's "entity_id" value
 * @method EntityActionRequired setNeedsExternalLinks()   Sets the current record's "needs_external_links" value
 * @method EntityActionRequired setNeedsWikiPage()        Sets the current record's "needs_wiki_page" value
 * @method EntityActionRequired setNeedsDescription()     Sets the current record's "needs_description" value
 * @method EntityActionRequired setNeedsFacts()           Sets the current record's "needs_facts" value
 * @method EntityActionRequired setNeedsSubtitle()        Sets the current record's "needs_subtitle" value
 * @method EntityActionRequired setEntity()               Sets the current record's "Entity" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseEntityActionRequired extends FoafRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_action_required');
        $this->hasColumn('entity_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('needs_external_links', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('needs_wiki_page', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('needs_description', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('needs_facts', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('needs_subtitle', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}