generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EntityAlias
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          entity_alias
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        entity_id:
          label: "Name"
        name:  
          label: "Alias"
      list:
        display: [ id, =entity, name, creator ]
      filter:
        display: [ entity_id, name, created_by ]
        
      form:
        display: [ entity_id, name, created_by ]
        
      edit:    ~
      new:     ~
