<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/11/23 13:01:02
sfConfig::add(array(
  'app_tuicachehandler_timeout' => 60,
  'app_recaptcha_public_key' => 'CHANGEME',
  'app_recaptcha_private_key' => 'CHANGEME',
  'app_email_from_address' => 'no-reply@example.com',
  'app_email_from_name' => 'WKW',
));
