<?php

/**
 * ContactMessages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    c4foaf
 * @subpackage model
 * @author     Tui Interactive Media
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
class ContactMessages extends BaseContactMessages
{
}
