<?php

/**
 * Home
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    c4foaf
 * @subpackage model
 * @author     Tui Interactive Media
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Home extends BaseHome
{
  
  public function preSave($event)
  {
    // Clean content
    $this->applyFilters();
  }
  
  public function applyFilters()
  {
    $this->set('feature_html', tuiHTMLFilter::clean($this->get('feature_html')));
    $this->set('feature_copy_intro', tuiHTMLFilter::clean($this->get('feature_copy_intro')));
    $this->set('feature_copy_extended', tuiHTMLFilter::clean($this->get('feature_copy_extended')));
    $this->set('callout_html', tuiHTMLFilter::clean($this->get('callout_html')));
  }
  
}
