<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoryFact extends BaseStoryFact
{
  
  public function preSave($event)
  {
    
    // Set default linking text
    if (!$this->_get('description')) {
      $this->set('description', $this->_get('Fact')->getTitle());
    }
    
  }


}