<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
  static public function retrieveForSelect($q, $limit) 
  {
    $query = Doctrine::getTable('sfGuardUser')->createQuery('u')
              ->where('u.username like ?', "%$q%")
              ->orderBy('u.username asc')
              ->limit(25);
    
    $entities = array();
    foreach( $query->fetchArray() as $entity)
    {
      $entities[ $entity['id'] ] = $entity['username'];
    }
    return $entities;
  }

}