<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addstoryversion extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('story_version', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'story_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'is_public' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'notnull' => true,
              'length' => 1,
             ),
             'created_by' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'version_comment' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
             ),
             'version' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'version',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
	}

	public function down()
	{
		$this->dropTable('story_version');
	}
}