<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Updatestory extends Doctrine_Migration
{
	public function up()
	{

    $this->addColumn('story', 'photo_url', 'string',  array(
         'type' => 'string',
         'length' => '255',
         ));
    $this->addColumn('story', 'photo_caption', 'string',  array(
         'type' => 'string',
         'length' => '255',
         ));
    $this->addColumn('story', 'photo_license', 'string',  array(
         'type' => 'string',
         'length' => '255',
         ));
    $this->addColumn('story', 'teaser', 'string',  array(
         'type' => 'string',
         'length' => '255',
         ));

	}

	public function down()
	{
    throw new Doctrine_Migration_IrreversibleMigrationException(
                'The remove column operation cannot be undone!'
            );
            
    // But in case you want to do it anyway....
    $this->removeColumn('story', 'photo_url');
    $this->removeColumn('story', 'photo_caption');
    $this->removeColumn('story', 'photo_license');
    $this->removeColumn('story', 'teaser');

	}
}