<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Updatestoryfact extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('story_fact', 'primary_entity', 'enum', array( 'type' => 'enum', 'values' => array( 0 => 'entity', 1 => 'related', ), ));
    $this->addColumn('story_fact', 'story_order', 'integer', array( 'type' => 'integer', ));
    $this->addColumn('story_fact', 'description', 'string', array( 'type' => 'string', 'length' => '255', ));
	}

	public function down()
	{
    throw new Doctrine_Migration_IrreversibleMigrationException(
                'The remove column operation cannot be undone!'
            );
            
    // But in case you want to do it anyway....
    $this->removeColumn('story_fact', 'primary_entity');
    $this->removeColumn('story_fact', 'story_order');
    $this->removeColumn('story_fact', 'description');

	}
}