<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Databasespelling extends Doctrine_Migration
{
	public function up()
	{
    // God, this is so pedantic, I'm sorry
    $this->renameColumn('story', 'photo_license', 'photo_licence');
    $this->renameColumn('entity', 'photo_license', 'photo_licence');
	}

	public function down()
	{
    $this->renameColumn('story',  'photo_licence', 'photo_license');
    $this->renameColumn('entity', 'photo_licence', 'photo_license');

	}
}