<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Entityactionstable extends Doctrine_Migration
{
	public function up()
	{
    
    
    $columns = array('id'                   => array('type' => 'integer',
                                                     'primary' => true,
                                                     'autoincrement' => true,
                                                     'length' => '8',
                                                    ),
                     'entity_id'            => array('type' => 'integer', 'length' => '8'),
                     'needs_external_links' => array('type' => 'integer', 'length' => '1'),
                     'needs_wiki_page'      => array('type' => 'integer', 'length' => '1'),
                     'needs_description'    => array('type' => 'integer', 'length' => '1'),
                     'needs_facts'          => array('type' => 'integer', 'length' => '1'),
                    );

    $options = array('type'     => 'INNODB','charset'  => 'utf8');

    $this->createTable('entity_action_required', $columns, $options);

    $this->addIndex('entity_action_required','entity_idx', array('fields' => array(0 => 'entity_id'), 'type' => 'unique'));
    

	}

	public function down()
	{
    $this->dropTable('entity_action_required');

	}
}