<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Factactionupgrade extends Doctrine_Migration
{
	public function up()
	{
    $this->removeColumn('fact_action_required', 'id');
    $this->changeColumn('fact_action_required', 'fact_id', 'integer', array(
         'type' => 'integer',
         'primary' => true,
         'length' => '8',));
    
    
	}

	public function down()
	{
    $this->addColumn('fact_action_required', 'id', 'integer', array('length' => 8, 'primary' => true, 'type' => 'integer'));
    $this->changeColumn('fact_action_required', 'fact_id', 'integer', array('primary' => false, 'type' => 'integer', 'length' => 8));
	}
}