<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Commentlength extends Doctrine_Migration
{
	public function up()
	{
    $this->changeColumn('story_comment', 'comment', 'string', array('length' => 1000, 'type' => 'string'));
    $this->changeColumn('fact_comment',  'comment', 'string', array('length' => 1000, 'type' => 'string'));
	}

	public function down()
	{
    $this->changeColumn('story_comment', 'comment', 'string', array('length' => 2147483647, 'type' => 'string'));
    $this->changeColumn('fact_comment',  'comment', 'string', array('length' => 2147483647, 'type' => 'string'));
	}
}