<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Storyversionupdate extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('story_version', 'subtitle', 'string', array('type' => 'string', 'length' => 255, ));
	}

	public function down()
	{
    $this->removeColumn('story_version', 'subtitle');
	}
}