<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Updatestorycomment extends Doctrine_Migration
{
	public function up()
	{
		$this->addColumn('story_comment', 'email', 'string', array('type' => 'string', 'length' => 255));
		$this->addColumn('story_comment', 'username', 'string', array('type' => 'string', 'length' => 255));
		$this->addColumn('story_comment', 'confirmation_token', 'integer', array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => 16));
		$this->addColumn('story_comment', 'email_confirmed', 'integer', array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => 1));
		$this->addColumn('story_comment', 'comment_approved', 'integer', array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => 1));
		
		$options = array('fields' => array('confirmation_token' => array()));	
		$this->addIndex('story_comment', 'confirmation_token', $options);
	}

	public function down()
	{
		$this->removeIndex('story_comment', 'confirmation_token');

		$this->removeColumn('story_comment', 'email');
		$this->removeColumn('story_comment', 'username');
		$this->removeColumn('story_comment', 'confirmation_token');
		$this->removeColumn('story_comment', 'email_confirmed');
		$this->removeColumn('story_comment', 'comment_approved');
	}
}