<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EarAddsubtitlecheck extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('entity_action_required', 'needs_subtitle', 'integer', array('length'=>1));
	}

	public function down()
	{
    $this->removeColumn('entity_action_required', 'needs_subtitle');
	}
}