<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version62 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('story', 'interest', 'integer', '2', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('story_version', 'interest', 'integer', '2', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('story', 'interest');
        $this->removeColumn('story_version', 'interest');
    }
}