<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version65 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('homepage', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'feature_html' => 
             array(
              'type' => 'string',
              'length' => '10240',
             ),
             'feature_copy_intro' => 
             array(
              'type' => 'string',
              'length' => '1024',
             ),
             'feature_copy_extended' => 
             array(
              'type' => 'string',
              'length' => '10240',
             ),
             'callout_html' => 
             array(
              'type' => 'string',
              'length' => '10240',
             ),
             'story1_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'story1_image_url' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'story2_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'story2_image_url' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'story3_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'story3_image_url' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'story4_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'story4_image_url' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('homepage');
    }
}