<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddisambiguationentity extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('disambiguation_entity', array(
             'disambiguation_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'entity_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'disambiguation_id',
              1 => 'entity_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
	}

	public function down()
	{
		$this->dropTable('disambiguation_entity');
	}
}