<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addentityurl extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('entity_url', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'entity_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 2147483647,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
             ),
             'urltype' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'created_by' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'foreign_id' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'created_at' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'equiv' => 
              array(
              'fields' => 
              array(
               0 => 'urltype',
               1 => 'foreign_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
	}

	public function down()
	{
		$this->dropTable('entity_url');
	}
}