<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfact extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('fact', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'entity_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 2147483647,
             ),
             'related_entity_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'start' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'end' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'created_by' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'fact_type_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'created_at' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
	}

	public function down()
	{
		$this->dropTable('fact');
	}
}