<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfactsource extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('fact_source', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'fact_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 1024,
             ),
             'source_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'is_supporting' => 
             array(
              'type' => 'integer',
              'length' => 1,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'created_by' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'created_at' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
	}

	public function down()
	{
		$this->dropTable('fact_source');
	}
}