<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addstoryfact extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('story_fact', array(
             'story_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'fact_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'story_id',
              1 => 'fact_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
	}

	public function down()
	{
		$this->dropTable('story_fact');
	}
}