<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Updatestoryversion extends Doctrine_Migration
{
	public function up()
	{

    $this->addColumn('story_version', 'photo_url', 'string',  array(
         'type' => 'string',
         'length' => '255',
         ));
    $this->addColumn('story_version', 'photo_caption', 'string',  array(
         'type' => 'string',
         'length' => '255',
         ));
    $this->addColumn('story_version', 'photo_licence', 'string',  array(
         'type' => 'string',
         'length' => '255',
         ));
    $this->addColumn('story_version', 'teaser', 'string',  array(
         'type' => 'string',
         'length' => '255',
         ));

	}

	public function down()
	{

    // But in case you want to do it anyway....
    $this->removeColumn('story_version', 'photo_url');
    $this->removeColumn('story_version', 'photo_caption');
    $this->removeColumn('story_version', 'photo_licence');
    $this->removeColumn('story_version', 'teaser');

	}
}