<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Factdateformats extends Doctrine_Migration
{
	public function up()
	{
	  
    $this->changeColumn('fact', 'start', 'date');
    $this->changeColumn('fact', 'end', 'date');
        

	}

	public function down()
	{
    $this->changeColumn('fact', 'start', 'timestamp');
    $this->changeColumn('fact', 'end', 'timestamp');
	}
}