<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Teasersize extends Doctrine_Migration
{
	public function up()
	{

    $this->changeColumn('story', 'teaser', 'string', array('length' => 512));
    
	}

	public function down()
	{
    $this->changeColumn('story', 'teaser', 'string', array('length' => 255));

	}
}