<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Factactiontable extends Doctrine_Migration
{
	public function up()
	{
    $columns = array('id'                   => array('type' => 'integer',
                                                     'primary' => true,
                                                     'autoincrement' => true,
                                                     'length' => '8',
                                                    ),
                     'fact_id'            => array('type' => 'integer', 'length' => '8'),
                     'needs_sources'      => array('type' => 'integer', 'length' => '1'),
                     'needs_description'  => array('type' => 'integer', 'length' => '1'),
                    );

    $options = array('type'     => 'INNODB','charset'  => 'utf8');

    $this->createTable('fact_action_required', $columns, $options);

    $this->addIndex('fact_action_required','fact_idx', array('fields' => array(0 => 'fact_id'), 'type' => 'unique'));

	}

	public function down()
	{
    $this->dropTable('fact_action_required');
	}
}