<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Entityactionupgrade extends Doctrine_Migration
{
	public function up()
	{
    $this->removeColumn('entity_action_required', 'id');
    $this->changeColumn('entity_action_required', 'entity_id', 'integer', array(
         'type' => 'integer',
         'primary' => true,
         'length' => '8',));
    
    
	}

	public function down()
	{
    $this->addColumn('entity_action_required', 'id', 'integer', array('length' => 8, 'primary' => true, 'type' => 'integer'));
    $this->changeColumn('entity_action_required', 'entity_id', 'integer', array('primary' => false, 'type' => 'integer', 'length' => 8));
	}
}