<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Entitytypeslug extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('entity_type', 'url_slug', 'string', array('type' => 'string', 'length' => 32, 'notnull' => true ));
  }

	public function down()
	{
	  throw new Doctrine_Migration_IrreversibleMigrationException(
        'The remove column operation cannot be undone!'
    );
    $this->removeColumn('entity_type', 'url_slug');
	}
	
	
}