<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Entitytypeslugunique extends Doctrine_Migration
{
  public function preUp()
  {
    
    $q = Doctrine_Query::create()->from('EntityType et')->execute();
    foreach($q as $et)
    {
      if (!$et->get('url_slug')) {
        $et->set('url_slug',$et->get('title'));
        $et->save();
      }
    }
      
  }



	public function up()
	{
    $this->addIndex('entity_type','slug_idx', array('fields' => array(0 => 'url_slug'), 'type' => 'unique'));

	}

	public function down()
	{
    $this->removeIndex('entity_type','slug_idx');

	}
}