<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Storysluggable extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('story', 'slug', 'string', array('length' => 255));
    $this->addColumn('story_version', 'slug', 'string', array('length' => 255));
    $this->addIndex('story', 'slug', array('fields' => array('slug'), 'type' => 'unique'));
    
	}

	public function down()
	{
    $this->removeColumn('story', 'slug');
    $this->removeColumn('story_version', 'slug');

	}
}