<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Storycommentalteration extends Doctrine_Migration
{
	public function up()
	{
		$this->changeColumn('story_comment', 'created_by', 'integer', array('type' => 'integer','notnull' => false,'length' => 4,));
		$this->changeColumn('story_comment', 'confirmation_token', 'string', array('type' => 'string','notnull' => false,'length' => 8,));
	}

	public function down()
	{
		$this->changeColumn('story_comment', 'created_by', 'integer', array('type' => 'integer','notnull' => true,'length' => 4,));
		$this->changeColumn('story_comment', 'confirmation_token', 'integer', array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length
' => 16));
	}
}