<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version60 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('contact_messages', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'message_type' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '32',
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'message' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '1000',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('contact_messages');
    }
}