<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version67 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->renameTable('homepage', 'home');
    }

    public function down()
    {
        $this->renameTable('home', 'homepage');
    }
}