<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version66 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('homepage', 'homepage_story1_id_story_id', array(
             'name' => 'homepage_story1_id_story_id',
             'local' => 'story1_id',
             'foreign' => 'id',
             'foreignTable' => 'story',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('homepage', 'homepage_story2_id_story_id', array(
             'name' => 'homepage_story2_id_story_id',
             'local' => 'story2_id',
             'foreign' => 'id',
             'foreignTable' => 'story',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('homepage', 'homepage_story3_id_story_id', array(
             'name' => 'homepage_story3_id_story_id',
             'local' => 'story3_id',
             'foreign' => 'id',
             'foreignTable' => 'story',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('homepage', 'homepage_story4_id_story_id', array(
             'name' => 'homepage_story4_id_story_id',
             'local' => 'story4_id',
             'foreign' => 'id',
             'foreignTable' => 'story',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->addIndex('homepage', 'homepage_story1_id', array(
             'fields' => 
             array(
              0 => 'story1_id',
             ),
             ));
        $this->addIndex('homepage', 'homepage_story2_id', array(
             'fields' => 
             array(
              0 => 'story2_id',
             ),
             ));
        $this->addIndex('homepage', 'homepage_story3_id', array(
             'fields' => 
             array(
              0 => 'story3_id',
             ),
             ));
        $this->addIndex('homepage', 'homepage_story4_id', array(
             'fields' => 
             array(
              0 => 'story4_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('homepage', 'homepage_story1_id_story_id');
        $this->dropForeignKey('homepage', 'homepage_story2_id_story_id');
        $this->dropForeignKey('homepage', 'homepage_story3_id_story_id');
        $this->dropForeignKey('homepage', 'homepage_story4_id_story_id');
        $this->removeIndex('homepage', 'homepage_story1_id', array(
             'fields' => 
             array(
              0 => 'story1_id',
             ),
             ));
        $this->removeIndex('homepage', 'homepage_story2_id', array(
             'fields' => 
             array(
              0 => 'story2_id',
             ),
             ));
        $this->removeIndex('homepage', 'homepage_story3_id', array(
             'fields' => 
             array(
              0 => 'story3_id',
             ),
             ));
        $this->removeIndex('homepage', 'homepage_story4_id', array(
             'fields' => 
             array(
              0 => 'story4_id',
             ),
             ));
    }
}