<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Fact extends BaseFact
{
  protected $start_is_partial = null;
  protected $end_is_partial   = null;
  protected $start_original   = null;
  protected $end_original     = null;
  
  

  public function getShortTitle($limit = 64) {
    $t = $this->getTitle();
    return strlen($t) > $limit ? substr($t, 0, $limit - 1) . '…' : $t;
  }





  public function preValidate($event) {
    if (strpos($this->get('start'), '00'))
    {
      $this->start_is_partial = true;
      $this->start_original   = $this->get('start');
      $this->set('start', $this->fixDate($this->get('start')));
    }

    if (strpos($this->get('end'), '00'))
    {
      $this->end_is_partial = true;
      $this->end_original   = $this->get('end');
      $this->set('end', $this->fixDate($this->get('end')));
    }

  }


  public function postValidate($event) {
    if ($this->start_is_partial) 
    {
      $this->set('start', $this->start_original);
    }
    
    if ($this->end_is_partial) 
    {
      $this->set('end', $this->end_original);
    }
    
  }



  protected function fixDate($date)
  {
    return str_replace('00','01', $date);
  }


}