<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoryRating extends BaseStoryRating
{
  

  public function preSave($event) 
  {
    
    $this->set('average_vote', $this->calculateAverage());
    
    return parent::preSave($event);
  }



  public function calculateAverage()
  { 
    $total = $this->getTotalVotes();
    
    if (!$total) return 0;
    
    $ar =  ((1 * $this->get('1_votes')) + 
            (2 * $this->get('2_votes')) + 
            (3 * $this->get('3_votes')) + 
            (4 * $this->get('4_votes')) + 
            (5 * $this->get('5_votes'))
           ) / $total;

    return $ar;
  }

  public function getTotalVotes()
  {
    return $this->get('1_votes') + $this->get('2_votes') + $this->get('3_votes') + $this->get('4_votes') + $this->get('5_votes');
  }

}