generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Home
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          home
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        is_active: { label: Published }
      list:
        display: [id, created_at, updated_at, is_active]
        sort: [updated_at, desc]
        object_actions:
          _edit:        false
          _delete:      false
          preview:   { label: Preview, action: preview }        
      
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
